### ISSUE TITLE
Route error messages customization

### ISSUE THREAD

**Issue by pv3ntur1** [diennea/carapaceproxy#185]
We need a way to customize error responses (error messages) from routes.
The solution is to bind to the route an "error-action" of type "static" (linked to corresponding error page.) to perform in case of error (the code - ex 500- is defined in the action.code)

Example config:
```
route.x.action=action
route.x.enabled=true
route.x.id=route_x
route.x.match=somethin
route.x.erroraction=action_error

action.x.id=action_error
action.x.type=static
action.x.resource=xxxxx
action.x.code=500
```

NOTE: the error "404 - Not found" is already customizable globally.

**Comment by hamadodene** [comment]
Note, if action linked to inexistent file,  we need to generate "not found error" (404).
I perfomed a test and I abtain this error:

```
SEVERE: Cannot load resource /data/carapace/default-error-pages/inexistent_page.html: java.io.IOException: cannot load resource /data/carapace/default-error-pages/inexistent_page.html, path must start with file: or classpath:
Jan 27, 2020 12:49:05 PM io.netty.channel.DefaultChannelPipeline onUnhandledInboundException
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.NullPointerException
        at org.carapaceproxy.server.StaticContentsManager.buildResponse(StaticContentsManager.java:59)
        at org.carapaceproxy.server.RequestHandler.serveStaticMessage(RequestHandler.java:402)
        at org.carapaceproxy.server.RequestHandler.clientRequestFinished(RequestHandler.java:327)
        at org.carapaceproxy.server.ClientConnectionHandler.channelRead0(ClientConnectionHandler.java:160)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:502)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)

```
