### ISSUE TITLE
ACME challenge token > Duplicated primary key Exception

### ISSUE THREAD

**Issue by hamadodene** [diennea/carapaceproxy#306]
```
Oct 26, 2021 3:16:06 PM org.carapaceproxy.server.certificates.DynamicCertificatesManager certificatesLifecycle
INFO: WAITING for certificate issuing process start for domain: hamatest97.example.it.
Oct 26, 2021 3:16:08 PM org.carapaceproxy.server.certificates.DynamicCertificatesManager createOrderForCertificate
INFO: Pending order location for domain hamatest97.example.it: https://acme-staging-v02.api.letsencrypt.org/acme/order/18582071/859911378
Oct 26, 2021 3:16:08 PM org.carapaceproxy.server.certificates.DynamicCertificatesManager createChallengeForCertificateOrder
INFO: Pending challenge data for domain hamatest97.example.it: {"type":"http-01","status":"pending","url":"https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/754462858/P03J7g","token":"zPve2QRwgyfOr2MJ7WkJXziNEGXZ1RQ7rSvwVERsNVo"}
Oct 26, 2021 3:16:08 PM herddb.server.ServerSideConnectionPeer handleSaslTokenMessage
INFO: client jvm-local connected as admin
Oct 26, 2021 3:16:08 PM herddb.client.HDBConnection waitForTableSpace
INFO: table space herd is up now: info {leader=pecora, replica=pecora, expectedreplicacount=1, tablespace_name=herd, maxleaderinactivitytime=0, uuid=640a142bf9bd401db4f2046d8d8f2981}
Oct 26, 2021 3:16:08 PM herddb.client.RoutedClientSideConnection handleGenericError
INFO: SQLIntegrityViolationException: java.sql.SQLIntegrityConstraintViolationException: herddb.model.DuplicatePrimaryKeyException: key 7a507665325152776779664f72324d4a37576b4a587a694e4547585a3152513772537677564552734e566f, decoded as zPve2QRwgyfOr2MJ7WkJXziNEGXZ1RQ7rSvwVERsNVo, already exists in table acme_challenge_tokens
Oct 26, 2021 3:16:08 PM org.carapaceproxy.configstore.HerdDBConfigurationStore saveAcmeChallengeToken
SEVERE: Error while performing saving of ACME challenge token with id: zPve2QRwgyfOr2MJ7WkJXziNEGXZ1RQ7rSvwVERsNVo data: zPve2QRwgyfOr2MJ7WkJXziNEGXZ1RQ7rSvwVERsNVo.apUiDFfwmP5YGEpO_vzK2vz71Xg4UTfIchczmJu8wNY
java.sql.SQLIntegrityConstraintViolationException: java.sql.SQLIntegrityConstraintViolationException: herddb.model.DuplicatePrimaryKeyException: key 7a507665325152776779664f72324d4a37576b4a587a694e4547585a3152513772537677564552734e566f, decoded as zPve2QRwgyfOr2MJ7WkJXziNEGXZ1RQ7rSvwVERsNVo, already exists in table acme_challenge_tokens
        at herddb.jdbc.utils.SQLExceptionUtils.wrapException(SQLExceptionUtils.java:42)
        at herddb.jdbc.HerdDBPreparedStatement.doExecuteLargeUpdateWithParameters(HerdDBPreparedStatement.java:571)
        at herddb.jdbc.HerdDBPreparedStatement.executeLargeUpdate(HerdDBPreparedStatement.java:558)
        at herddb.jdbc.HerdDBPreparedStatement.executeUpdate(HerdDBPreparedStatement.java:547)
        at org.carapaceproxy.configstore.HerdDBConfigurationStore.saveAcmeChallengeToken(HerdDBConfigurationStore.java:441)
        at org.carapaceproxy.server.certificates.DynamicCertificatesManager.createChallengeForCertificateOrder(DynamicCertificatesManager.java:423)
        at org.carapaceproxy.server.certificates.DynamicCertificatesManager.certificatesLifecycle(DynamicCertificatesManager.java:295)
        at org.carapaceproxy.server.certificates.DynamicCertificatesManager.lambda$run$0(DynamicCertificatesManager.java:273)
        at org.carapaceproxy.cluster.impl.ZooKeeperGroupMembershipHandler.executeInMutex(ZooKeeperGroupMembershipHandler.java:297)
        at org.carapaceproxy.server.certificates.DynamicCertificatesManager.run(DynamicCertificatesManager.java:271)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)

```

**Comment by pv3nturi** [comment]
This might has been fixed with https://github.com/diennea/carapaceproxy/pull/379. We may close this ad eventually reopen it, ok @hamadodene?
