### ISSUE TITLE
Jetty > Carapace does not start with wildcard certificate

### ISSUE THREAD

**Issue by hamadodene** [diennea/carapaceproxy#317]
With jetty update to 9.4.44.v20210927, Carapace is no longer able to boot with an https certificate configured for the admin interface:
My carapace versione is: 1.7.0

My ssl configuration in server.properties:

http.admin.enabled=true
#http.admin.port=-1
http.admin.host=server_hostname
https.admin.port=8001
https.admin.sslcertfile=diennea.lan-2017-2027.p12
https.admin.sslcertfilepassword=xxxxxxxxxxxxxxxxxx
admin.advertised.host=server_hostname

```
2022-01-31 11:38:49.465:WARN:oejuc.AbstractLifeCycle:main: FAILED Server@76e2a621{FAILED}[9.4.44.v20210927]: java.lang.IllegalStateException: KeyStores with multiple certificates are not supported on the base class org.eclipse.jetty
.util.ssl.SslContextFactory. (Use org.eclipse.jetty.util.ssl.SslContextFactory$Server or org.eclipse.jetty.util.ssl.SslContextFactory$Client instead)
java.lang.IllegalStateException: KeyStores with multiple certificates are not supported on the base class org.eclipse.jetty.util.ssl.SslContextFactory. (Use org.eclipse.jetty.util.ssl.SslContextFactory$Server or org.eclipse.jetty.ut
il.ssl.SslContextFactory$Client instead)
at org.eclipse.jetty.util.ssl.SslContextFactory.newSniX509ExtendedKeyManager(SslContextFactory.java:1289)
at org.eclipse.jetty.util.ssl.SslContextFactory.getKeyManagers(SslContextFactory.java:1271)
at org.eclipse.jetty.util.ssl.SslContextFactory.load(SslContextFactory.java:373)
at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:244)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:97)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:321)
at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
at org.eclipse.jetty.server.Server.doStart(Server.java:401)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
at org.carapaceproxy.core.HttpProxyServer.startAdminInterface(HttpProxyServer.java:343)
at org.carapaceproxy.launcher.ServerMain.start(ServerMain.java:163)
at org.carapaceproxy.launcher.ServerMain.main(ServerMain.java:127)
Ctrl-C trapped. Shutting down
2022-01-31 11:38:51.603:DBUG:oejuc.AbstractLifeCycle:ctrlc-hook: stopping Server@76e2a621{FAILED}[9.4.44.v20210927]
2022-01-31 11:38:51.603:DBUG:oejs.Server:ctrlc-hook: doStop Server@76e2a621{STOPPING}[9.4.44.v20210927]
```

**Comment by hamadodene** [comment]
As a workaround we have eliminated all aliases inherent to the certificate in cacerts with the command:

`keytool -alias 1  -delete  -keystore /etc/ssl/diennea.lan/diennea.lan-2017-2027.p12 -storepass `
