### ISSUE TITLE
Manul certificate > MalformedURLException  when loadCertificateForDomain

### ISSUE THREAD

**Issue by hamadodene** [diennea/carapaceproxy#411]
Updating with version 1.9 (From 1.8) of carapace we got this error when trying to understand a manual certificate.

```
Feb 20, 2023 8:51:39 AM org.carapaceproxy.configstore.HerdDBConfigurationStore loadCertificateForDomain
SEVERE: Error while performing Certificate loading for domain be-qasql.sviluppo.dna.
java.net.MalformedURLException: no protocol:
        at java.base/java.net.URL.<init>(URL.java:674)
        at java.base/java.net.URL.<init>(URL.java:569)
        at java.base/java.net.URL.<init>(URL.java:516)
        at org.carapaceproxy.configstore.HerdDBConfigurationStore.loadCertificateForDomain(HerdDBConfigurationStore.java:419)
        at org.carapaceproxy.server.certificates.DynamicCertificatesManager.loadOrCreateDynamicCertificateForDomain(DynamicCertificatesManager.java:226)
        at org.carapaceproxy.server.certificates.DynamicCertificatesManager.loadCertificates(DynamicCertificatesManager.java:211)
        at org.carapaceproxy.server.certificates.DynamicCertificatesManager.reloadConfiguration(DynamicCertificatesManager.java:176)
        at org.carapaceproxy.core.HttpProxyServer.applyDynamicConfiguration(HttpProxyServer.java:720)
        at org.carapaceproxy.core.HttpProxyServer.configureAtBoot(HttpProxyServer.java:527)
        at org.carapaceproxy.launcher.ServerMain.start(ServerMain.java:160)
        at org.carapaceproxy.launcher.ServerMain.main(ServerMain.java:127)
```

![image](https://user-images.githubusercontent.com/43852233/220048137-7762b3fc-dc80-4724-b0ed-c46db21e56e3.png)

Other instances of carapace that didn't have a manual certificate were updated without problems

**Comment by hamadodene** [comment]
Investigating I noticed that the problem is related to the fact that in version 1.8 of Carapace when a manual certificate was loaded, it was loaded with pedingorder=" ":

```
CertificateData cert = new CertificateData(domain, "", encodedData, state, "", "");
cert.setManual(MANUAL.equals(certType));
```
```
    public CertificateData(String domain, String privateKey, String chain, DynamicCertificateState state,
                           String orderLocation, String challengeData) {
        this.domain = domain;
        this.privateKey = privateKey;
        this.chain = chain;
        this.state = state;
        this.pendingOrderLocation = orderLocation;
        this.pendingChallengeData = challengeData;
    }
```

While from the new version (1.9) we load pendingorder=null.
Introduce here https://github.com/diennea/carapaceproxy/pull/386

```
CertificateData cert = new CertificateData(domain, encodedData, state);
cert.setManual(MANUAL.equals(certType));

```
```
    public CertificateData(String domain,
                           String chain,
                           DynamicCertificateState state) {
        this(domain, null, chain, state, null, null);
    }
```

**Comment by hamadodene** [comment]
I Fix that setting pendingorder to null for manual certificates
